# Faye
development:
  server: "http://0.0.0.0:9292/faye"
  adapter_javascript_url: "http://0.0.0.0:9292/faye/faye.js"
  auth_token: DEVELOPMENT_SECRET_TOKEN
  adapter: "Faye"
  async: true

# Pusher
# development:
#   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
#   app_id: "YOUR_PUSHER_APP_ID"
#   api_key: "YOUR_PUSHER_API_KEY"
#   auth_token: "YOUR_PUSHER_SECRET"
#   adapter: "Pusher"
#   async: true

# Disabled
# development:
#   adapter: false

test:
  server: "http://0.0.0.0:9292/faye"
  adapter_javascript_url: "http://0.0.0.0:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "secret"
  async: false

production:
  server: "http://example.com/faye"
  adapter_javascript_url: "http://0.0.0.0:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "9ed7ddb0071d28ae40b146f4027d2d52b68a0563ce68beda81265b1d85a330c0"
  async: true
